version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
